### ISSUE TITLE
Links are not allowed

### ISSUE THREAD

**Issue by nastya-kostyukova** [phw/showdown-htmlescape#25]
ex. link to <http://www.google.com/>
It's displayed as a text in result

**Comment by phw** [comment]
Sorry for the late reply, totally missed your issue report. About the issue: Auto linking URLs is not really part of this extension, but showdown itself does have the `simplifiedAutoLink` for this. So the following code:

```javascript
var converter = new showdown.Converter({
    extensions: ['htmlescape'],
    simplifiedAutoLink: true
})
console.log(converter.makeHtml('http://www.google.com'))
```

Should output:

```
<p><a href="http://www.google.com">http://www.google.com</a></p>
```

Hope that helps. I am closing this issue, but feel free to reopen if you have another question / issue.
